language: python
python:
- '2.7'
install:
- pip install -U setuptools
script: true
after_success: python build.py --command="sdist bdist_wheel"
deploy:
  provider: releases
  api_key:
    secure: kT+6kqWJEMmyTxWM6IdnksvjXa8YbUiSNtlpkHIGVjd2PQQbsemY/1wZcjdBF9nq0dh5r9JFWAV3Ms8F3U8QWUHG2jfhvplN+0iJGb5rCsM1SU1K6v4gCoU8LKs8AXVJZYbJBGi3gBSMaHpuSpUTeXG5CwMsiddBszi/SAWQ8xLBNUqpyUQe5DobyOS+iTSgX3dYjSOXHzW3Uap/TfrkiTj1o33FWYimd2UBwF1MdgnzEQWXUF4FBI9ydiOkKzpjF+fIOIp+uo+yaSoFqeKvNk8EsU74fg7aToj4T1rXIgrFbGq4+dOccYHiGX/DKUGb+RoUo7Dw4e8hKZ3pG89HhN1cgBeEqPol/aWi4ZEqENL2PINXE4uKLIe2e0/arNYlmst7weplMTZd5JEQwCqLT+VvQjjTHrpm49PaBcLCmOwa8EdB6c08BemPe98p9N1OO+mJG0PkbBdsbjzCXGOv4X4/ENonzpQvYmjxw6y1K6Iv7H8K1d2B1xLY7me4M3FTqEGmNs9MfJnprkdkvoZqPI/rrEpXFBMuBi3/p/ryHHU4luCuWrQXesATcgw+Dix0Vkj//YtLKGFGkVSVTtCpCooOEKgsGHeHrsusJ1ZuT5XGSTHF+5Qxw9+YQwJS5KDjYv11wnBcUma9pq9ByLFWfVrRnoI+a/BIwy6FPMLShQw=
  skip_cleanup: true
  file_glob: true
  file:
  - "dist/oem-database-anidb-imdb*"
  - "dist/oem_database_anidb_imdb*"
  on:
    repo: KingJ/oem-database-anidb-imdb
    tags: true
